"""add customer and addresses table

Revision ID: 267fa0299cb7
Revises: 49e791333a18
Create Date: 2021-05-22 09:30:18.194848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267fa0299cb7'
down_revision = '49e791333a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('social_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('complement', sa.String(), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_addresses')
    op.drop_table('customers')
    # ### end Alembic commands ###
