"""add stock table

Revision ID: 88359808368e
Revises: 267fa0299cb7
Create Date: 2021-05-22 09:55:16.353283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88359808368e'
down_revision = '267fa0299cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_stock',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_stock')
    # ### end Alembic commands ###
